# Generated by Django 3.2.4 on 2021-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
