# Generated by Django 3.2.4 on 2021-06-08 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_users_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=45)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_board_list',
            },
        ),
        migrations.CreateModel(
            name='WorkflowBoard',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=100)),
                ('board_description', models.CharField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='user_management.users')),
            ],
            options={
                'db_table': 'project_board',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
                ('card_desciption', models.CharField(max_length=254)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('board_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='workflow.boardlist')),
            ],
            options={
                'db_table': 'project_list_card',
            },
        ),
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='workflow.workflowboard'),
        ),
    ]
