# Generated by Django 3.2.4 on 2021-06-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardlist',
            old_name='created_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='workflowboard',
            old_name='created_on',
            new_name='updated_on',
        ),
    ]
