# Generated by Django 3.2.4 on 2021-06-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20210609_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_list', to='workflow.workflowboard'),
        ),
    ]
