# Generated by Django 3.2.4 on 2021-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_card_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
