# Generated by Django 3.2.4 on 2021-06-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_card_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_desciption',
            new_name='card_description',
        ),
    ]
