# Generated by Django 3.2.4 on 2021-06-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_rename_card_desciption_card_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_ref', models.TextField(default=None)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='workflow.card')),
            ],
            options={
                'db_table': 'card_attachment',
            },
        ),
    ]
